secrets:
    REDIS_URL: ENC[AES256_GCM,data:Rc3Q42BvTXBbAz77byTsYhrV5JB2IdzlMxatjKnRrfdOyE/LRHIepxBQRSq1d0U8GvI3GeHK6lrg55GZ+G3HrDK6Z2caZFQJcHqrrKeDFP6QlCld43JLC37JMDubFE/E6wqDH2Pa,iv:HqNrWW+8p2tY17BEAN2Nj9Au2gFVEyej9H+iuYakKiA=,tag:1ivTdGgebNFHxyaVLHRLmw==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:zbC8oRH5wcJieQI5fu9/aPCdEs0G5dDg/I/k/OTA29MKnLZR/y0RkGKLOH9gjbVtkXdB5Lm+4vLd2EkJHoQ5An8fRYCXcbHQ,iv:dR0+hUdL1xtFsNRSoQdhXTIRnSLsymbLquZzbaGPfCw=,tag:YrTGstxnIfBvR+vJpQrCSw==,type:str]
    DISCORD_ADMIN_IDS: ENC[AES256_GCM,data:bkO7diZUd8TSFBb3H3GQP0Va,iv:Cd/vZaSoGEIuibNTCYW/MKSCEwitTWK64JjtGW9wpH4=,tag:InWrIDF2dhd482jHNS1DTg==,type:str]
    DISCORD_SERVER_IDS: ENC[AES256_GCM,data:NqvPzd44MXOxSRRHmBQBmPOiqvi/o9ggF9vdNPQwSOKz8JufbA==,iv:/zf1VJi+59Kglv1nwKWAuYZ1ipozS1oTUVWlwzcfAk4=,tag:ZNMNvWjtVEvKElRAec1BtQ==,type:str]
    TWITTER_DISCORD_CHANNELS: ENC[AES256_GCM,data:7sfKWleS7kqIwHTiea0zn73zew==,iv:UKFIY3eHcpJSU4FbdvqBQGJOxByernwcvteVwwqCY0M=,tag:zg7zrtLfZo/CH2EIHzkPQg==,type:str]
    TWITTER_FEED: ENC[AES256_GCM,data:/Lf6WPlZIyieIi2RVHeyoqvJ28r6mFIdL2IrNoFjiBZe6xOXQzbnXuIT,iv:icN7T0A6SWLbIAc8NXFM5vniR1IarGj63un2ZLPEkMo=,tag:zwaDl+kYCqjwSo01phJpBw==,type:str]
    GAME_UPDATES_DISCORD_CHANNELS: ENC[AES256_GCM,data:xWHKA5PqWHaMG90vVNe0ppkf8jWR45Yx7jbE3fKrlvmSuCZTLLz/,iv:Wca+xenpZNNk2xRlZvpX2byK39dYlRZV6GafKFv0v0I=,tag:xByFq3GcKcxX8UW3j+F2OQ==,type:str]
    GW_WIKI_USERNAME: ENC[AES256_GCM,data:1JI/Zxv0IZMLVY+KMzcAESx+cVCBiAk=,iv:SBMBOP+n9xSRp+jhlNla3wb8F2e5kpQNXFwBqXrGzg4=,tag:tO+C9z1uVKs0hW66KlxQ4w==,type:str]
    GW_WIKI_PASSWORD: ENC[AES256_GCM,data:pL2DtI2i3FqXY0+N7dyYg0IWMmBdoFIobCUKp7/p8Cs=,iv:10M091clUPERNKYfK6bXSrFIa2k9f+SKgYiDdnES2Es=,tag:LJ40vfTOAT+WwtYOQd9Hzg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:694674006091:key/76595233-7eb5-49f9-b930-dd1c6bd470c5
          created_at: "2026-07-29T17:03:59Z"
          enc: AQICAHg0pAjcxeE5DUSK5jhcI4HJxc+R2V8Cn0dgs2gtsyBibwFGjz/YKx1cKRPoQRCy8ZPBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMX5GFM5ktSwtmqIojAgEQgDsWk1gaPt8+EsJLO5+S1iXkRuRGUyTMTchP98KaQDl7GWvianYfLBFMS8x75oGlpOGEQNjyRdzxqK5gYw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-29T17:03:59Z"
    mac: ENC[AES256_GCM,data:MUzqp19UaML8Mo6MnOmc4o8H/KvaKHZ3mCObtKnZHXQ1/TyVvc7K/37Ua1JcTYXbdzJOnH/5K3nyilg2mMm7T7aorERHiVcxt5Bx1Ns14Y305EChLXLEb3rF66G+8R+XN6qE1Un2ansHBGT/FKd8XhCK4T3lxWgzYXzTMiOUJjQ=,iv:67p+Gv3LU/TEEet1GO39pVeZ11xhXmrKyPwYRbyI1mo=,tag:R8XZT2/+gNHui/lcjpVmDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
